"""Multisensor analysis across Sentinel-1, Sentinel-2 and Sentinel-3."""

from .catalog import ProductRef, select_product_refs
from .cache import AssetCache
from .atmosphere import ColumnToSurfaceConfig, column_to_surface_estimate
from .cities import CitySpec, get_city, list_cities
from .config import AOI, ClientConfig
from .cube import AnalysisGrid, CubeValidationError, GridSpec, tag_cube, validate_cube, validate_observation_set
from .downscale import (CoarseConsistentDownscaler, GWRDownscaler, LinearDownscaler, RandomForestDownscaler,
                        XGBoostDownscaler, fit_coarse_consistent_gwr_downscaler,
                        fit_coarse_consistent_linear_downscaler, fit_coarse_consistent_random_forest_downscaler,
                        fit_coarse_consistent_tsharp_downscaler, fit_coarse_consistent_xgboost_downscaler,
                        fit_gwr_downscaler, fit_linear_downscaler, fit_random_forest_downscaler,
                        fit_tsharp_downscaler, fit_xgboost_downscaler, fuse_estarfm, fuse_starfm, reaggregate_to_target,
                        split_spatiotemporal, validate_downscaler, validate_reaggregation)
from .download import CDSEDownloader
from .fusion import TemporalMatch, TemporalPolicy, align_features, fusion_quality
from .harmonization.spatial import SpatialResamplingPolicy
from .thermal import heat_hazard_metrics
from .sensors.sentinel1 import (
    Sentinel1Catalog,
    S1ARDProcessingConfig,
    Sentinel1ProcessingConfig,
    Sentinel1ProcessingResult,
    Sentinel1ReadConfig,
    Sentinel1RTCConfig,
    build_s1_graph,
    process_s1_grd,
    process_s1,
    process_s1_ard,
    process_s1_rtc,
    read_s1_ard,
    read_s1_grd,
    read_s1_rtc,
    sentinel1_indices,
)
from .sensors.ecostress import EcostressCatalog, read_ecostress_lst
from .sensors.landsat import LandsatCatalog, read_landsat_lst
from .sensors.sentinel2 import (
    SENTINEL2_L1C_PRODUCT_TYPE,
    Sentinel2Catalog,
    Sentinel2L1CReadConfig,
    Sentinel2ReadConfig,
    compose_s2,
    read_s2_l1c,
    read_s2_l2a,
    scl_valid_mask,
    sentinel2_coverage,
    sentinel2_indices,
)
from .sensors.sentinel5p import Sentinel5PCatalog, Sentinel5PReadConfig, grid_s5p, read_s5p_l2
from .sensors.sentinel3 import (
    CDSECatalog,
    LSTExceptionFlag,
    ProductFormatError,
    ProductQuery,
    QualityPolicy,
    Sentinel3LST,
    Sentinel3LSTClient,
    apply_quality_mask,
    cf_flag_mask,
    cf_flag_mask_array,
    daily_mean,
    grid_l2_lst,
    inspect_l2_lst,
    quality_summary,
    read_l2_lst,
    statistics,
    to_celsius,
)
from .storage import open_zarr, read_cog, validate_cog, write_cog, write_zarr
from .stac import STACCatalog, STACItem
from .metadata import apply_variable_contract, ensure_compatible_units, validate_variable_contract
from .reference import collocate_stations
from .providers import AUXILIARY_PROVIDERS, AuxiliaryArtifact, AuxiliarySpec, CAMSConfig, CAMSProvider, CarbonMapperConfig, CarbonMapperProvider, ERA5Config, ERA5Provider, OpenAQConfig, OpenAQInterpolationConfig, OpenAQProvider
from .validation import blocked_spatiotemporal_split, compare_to_reference, validate_independent_reference
from .workflow import AnalysisRequest, AnalysisResult, AnalysisWorkflow, TemporalPair, select_temporal_pair

__all__ = [
    "AOI",
    "AssetCache",
    "ColumnToSurfaceConfig",
    "AnalysisGrid",
    "AnalysisRequest",
    "AnalysisResult",
    "AnalysisWorkflow",
    "AUXILIARY_PROVIDERS",
    "AuxiliaryArtifact",
    "AuxiliarySpec",
    "CAMSConfig",
    "CAMSProvider",
    "CarbonMapperConfig",
    "CarbonMapperProvider",
    "CoarseConsistentDownscaler",
    "GWRDownscaler",
    "CDSECatalog",
    "CDSEDownloader",
    "CitySpec",
    "ClientConfig",
    "CubeValidationError",
    "GridSpec",
    "LSTExceptionFlag",
    "LinearDownscaler",
    "ProductFormatError",
    "ProductQuery",
    "ProductRef",
    "select_product_refs",
    "QualityPolicy",
    "OpenAQConfig",
    "OpenAQInterpolationConfig",
    "OpenAQProvider",
    "ERA5Config",
    "ERA5Provider",
    "RandomForestDownscaler",
    "XGBoostDownscaler",
    "LandsatCatalog",
    "EcostressCatalog",
    "Sentinel1Catalog",
    "S1ARDProcessingConfig",
    "Sentinel1ProcessingConfig",
    "Sentinel1ProcessingResult",
    "Sentinel1ReadConfig",
    "Sentinel1RTCConfig",
    "Sentinel2Catalog",
    "Sentinel2ReadConfig",
    "Sentinel2L1CReadConfig",
    "SENTINEL2_L1C_PRODUCT_TYPE",
    "Sentinel5PCatalog",
    "Sentinel5PReadConfig",
    "Sentinel3LST",
    "Sentinel3LSTClient",
    "SpatialResamplingPolicy",
    "STACCatalog",
    "STACItem",
    "TemporalMatch",
    "TemporalPolicy",
    "TemporalPair",
    "select_temporal_pair",
    "align_features",
    "apply_variable_contract",
    "apply_quality_mask",
    "build_s1_graph",
    "cf_flag_mask",
    "cf_flag_mask_array",
    "compare_to_reference",
    "blocked_spatiotemporal_split",
    "column_to_surface_estimate",
    "collocate_stations",
    "compose_s2",
    "daily_mean",
    "fit_linear_downscaler",
    "fit_coarse_consistent_linear_downscaler",
    "fit_coarse_consistent_random_forest_downscaler",
    "fit_random_forest_downscaler",
    "fit_tsharp_downscaler",
    "fit_xgboost_downscaler",
    "fit_gwr_downscaler",
    "fit_coarse_consistent_tsharp_downscaler",
    "fit_coarse_consistent_xgboost_downscaler",
    "fit_coarse_consistent_gwr_downscaler",
    "fuse_starfm",
    "fuse_estarfm",
    "fusion_quality",
    "grid_l2_lst",
    "grid_s5p",
    "get_city",
    "heat_hazard_metrics",
    "ensure_compatible_units",
    "inspect_l2_lst",
    "list_cities",
    "open_zarr",
    "process_s1_grd",
    "process_s1",
    "process_s1_ard",
    "process_s1_rtc",
    "quality_summary",
    "read_l2_lst",
    "read_cog",
    "read_s1_grd",
    "read_ecostress_lst",
    "read_landsat_lst",
    "read_s1_ard",
    "read_s1_rtc",
    "read_s2_l2a",
    "read_s2_l1c",
    "read_s5p_l2",
    "reaggregate_to_target",
    "scl_valid_mask",
    "sentinel2_coverage",
    "sentinel1_indices",
    "sentinel2_indices",
    "statistics",
    "split_spatiotemporal",
    "tag_cube",
    "to_celsius",
    "validate_cube",
    "validate_observation_set",
    "validate_downscaler",
    "validate_independent_reference",
    "validate_cog",
    "validate_reaggregation",
    "validate_variable_contract",
    "write_cog",
    "write_zarr",
]
